### ISSUE TITLE
Remove node_modules folder

### ISSUE THREAD

**Issue by palhimanshu1991** [ankitkhadria1/node-scrapper-zomato#1]
node_modules folder is not required in the repository, package.json is enough. Just like we don't need vendors folder in case of laravel only composer.json & composer.lock are enough.

**Comment by ankitkhadria1** [comment]
i know actually i didn't ignore it in  .gitignore  because i have a very
slow net connection i can't install it again and again and later i will
remove it
but thanks for advise.
